### PR TITLE
Add EDAC memory error rules

### PR DESCRIPTION
**Pull request by robert-will-brown**

### CODE REVIEW

**Comment by samber** [comment]
Same question of the other PR:

Should we alert from the first error ? Or tolerate a threshold 
Should we consider such error as rare ?

**Comment by robert-will-brown** [comment]
Using this [Google study](http://www.cs.toronto.edu/~bianca/papers/sigmetrics09.pdf) for reference.

1. An Uncorrectable error will typically force the host system to panic / crash.
2. A Correctable error will typical be, as the name suggests, corrected by the ECC memory and go unnoticed by the user.

An uncorrectable error is preceded by a correctable error 70–80 percent of the time. A correctable error increases the probability of an uncorrectable error by factors of 9–400.

Given the above, perhaps I should modify: 

- "HostEDACUncorrectableErrorsdetected" to severity "error" when > 1.
- "HostEDACCorrectableErrorsdetected" stay the same.

A threshold is difficult with the Correctable Errors, I've seen one system with millions of Correctable memory errors.  Do you think the "increase" isn't the correct way to capture it?

Comments appreciated.

**Comment by paulfantom** [comment]
What are the action item for Correctable Errors and Uncorrectable Errors? I mean what the operator needs to do if such alerts fire?

How does such an alert affect the user?

**Comment by robert-will-brown** [comment]
As per the linked document, google replace DIMMS aggressively when they show Uncorrectable errors.

> In many production environments, including ours, a single un-correctable error is considered serious enough to replace the dual in-line memory module (DIMM) that caused it.

**Comment by paulfantom** [comment]
> As per the linked document, google replace DIMMS aggressively when they show Uncorrectable errors.

Fair.

---

What about Correctable Errors? Because it looks to me like `severity` isn't what it should be as there is no direct action item for this alert. Especially considering that the same document says:
> If done well, the handling of correctable memory errors is largely invisible to application software.

**Comment by robert-will-brown** [comment]
> What about Correctable Errors? Because it looks to me like severity isn't what it should be as there is no direct action item for this alert....

True, but I think this is the salient line:

> An uncorrectable error is preceded by a correctable error 70–80 percent of the time. A correctable error increases the probability of an uncorrectable error by factors of 9–400.

Means there should be an alert I think?  Could you recommend the `severity` you think appropriate?

**Comment by paulfantom** [comment]
I would say something like `info` is appropriate here. This way you also have nice grading of those alerts since one responsible for Correctable Errors is a `warning` type.

**Comment by robert-will-brown** [comment]
Update as per discussion.

**Pull request merged**
