### PR TITLE
Network transmit errors

### PR DESCRIPTION
**Pull request by robert-will-brown**
Detect increase in transmit or receive network errors.

### CODE REVIEW

**Comment by samber** [comment]
Should we alert from the first error ? Or tolerate a threshold ?

I checked on multiple servers with years of uptime but I get 0 everywhere. 😅

Should we consider such error as rare ?

**Comment by robert-will-brown** [comment]
I'm not sure what the definition of "rare" is but my experience this is quite infrequent.

Checking 100+ systems and only one is displaying this issue averaging at 60 receive errors a minute.

Can you suggest an alteration to the rules?  Not sure how else to approach this, especially given the difficult in tracking down systems exhibiting the problem 😃

**Comment by paulfantom** [comment]
If those are infrequent, then doesn't an overlaying protocol handle this? I mean TCP has retransmission capabilities, so what would be the impact on end-user of having a small number of network rx/tx errors?

**Comment by robert-will-brown** [comment]
I think you would want to initiate some troubleshooting if you were to see this as `errors`can result from faulty cables, faulty NIC or switch port and speed or duplex mismatch.

**Comment by samber** [comment]
Ok, if this is not frequent, let's trigger an alert from the first error.

Can you just add `> 0` at the end of queries please ? I'm going to merge just after. 👌

**Comment by robert-will-brown** [comment]
Done @samber.

**Pull request merged**
