### PR TITLE
added some extra MySQL checks

### PR DESCRIPTION
**Pull request by mcrauwel**

### CODE REVIEW

**Comment by samber** [comment]
Hi @mcrauwel and thanks for contributing !

Why do you use `avg by (instance)` on every series ?

**Comment by mcrauwel** [comment]
Hi @samber, that makes it more readable here... I'm using these checks in PMM (https://www.percona.com/software/database-tools/percona-monitoring-and-management). Maybe PMM add more metadata than regular prometheus installations...

And I got the idea from some other checks in the list ;)

**Comment by samber** [comment]
There is only 1 mysql engine exported per exporter (unlike postgresql exporter), so IHMO you can remove `avg by (instance)`. 

And in some case it may reduce data accuracy.

For example, `mysql_global_variables_max_connections` is exported only once per target scrape. I think there is no reason for avg aggregations.

However, it is necessary in queries having `*** and ***`. But it should be replaced by `*** and ON (instance) ***`. Example here: https://github.com/samber/awesome-prometheus-alerts/blob/master/_data/rules.yml#L349

The rest of the contribution looks good. 👌

I look forward to see more checks! ;)

**Comment by mcrauwel** [comment]
I removed avg grouping where possible...

For the percentage calculation for the `threads_connected` or `threads_running` vs `max_connections`, I could not get it working in Prometheus without the grouping...

**Comment by mcrauwel** [comment]
example:
Screenshot 2020-03-31 at 11 47 01
Screenshot 2020-03-31 at 11 47 28

**Comment by samber** [comment]
Ok, I see. It works [here](https://metrics.privacybydesign.foundation/prometheus/graph?g0.range_input=1h&g0.expr=(mysql_global_status_threads_connected%20%2F%20mysql_global_variables_max_connections)%20*%20100&g0.tab=1), but I suppose you have different labels on mysql_global_variables_max_connections and mysql_global_status_threads_connected.

Let's merge.

**Comment by ivanovv** [comment]
Looking at the docs https://prometheus.io/docs/prometheus/latest/configuration/alerting_rules/ I can't find `$instance` mentioned.

when I try to copy rules I get this error:
```
/root/.ansible/tmp/ansible-tmp-1588707513.581442-216390171292376/source: group \"node-exporter\", rule 4, \"MysqlSlaveIoThreadNotRunningOn{{$instance.instance}}\": annotation \"summary\": template: __alert_MysqlSlaveIoThreadNotRunningOn{{$instance.instance}}:1: undefined variable \"$instance\"
```

What is `{{ $instance.instance }}`?

**Comment by mcrauwel** [comment]
🤦 it needs to be $labels.instance

**Comment by ivanovv** [comment]
Thanks for such a prompt reply!

Still trying to understand though.
If I do a replacement, then it will look something like this
```
annotations:
  summary: "MySQL Slave SQL thread not running on {{ $labels.instance }} (instance {{ $labels.instance }})"
```
For my data that will give me

```MySQL Slave SQL thread not running on mysql-1 (instance mysql-1)```

Not sure I understand the point of having `{{ $labels.instance }}` two times in one line.

**Comment by samber** [comment]
Instance is not expected in rule name.

Only summary should have this information.

I just publish a fix.

**Pull request merged**
