### PR TITLE
feat: adding hadoop jmx exporter

### PR DESCRIPTION
**Pull request by vickywilsonj**

### CODE REVIEW

**Comment by samber** [comment]
Hi @vickywilsonj and thanks for this first contrib.

Could you please add this config to _data/rules.yml instead ? 🙏

**Comment by vickywilsonj** [comment]
Hi @samber Thank you! added to the rules.yml and renamed the exporter to jmx-exporter

**Comment by samber** [comment]
I will move it to the right section: "Database". Thanks for the contrib ;)

**Comment by vickywilsonj** [comment]
Thanks @samber appreciate it!

**Pull request merged**
